version: '3.8'

services:
  mcp-ufc:
    build: .
    ports:
      - "8005:8005"
    environment:
      - PYTHONUNBUFFERED=1
      - UFC_DEBUG=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs: 